# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Moran Rozenszajn
title: RT Embedded software developer/team lead
email: moriki@gmail.com
phone: +972-545660849

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Moran296
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: moran-rozenszajn
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Moran, an RT embedded developer and team lead, with experience in different embedded IOT products ranging from home automation to agriculture and medical fields. I am enthusiastic about learning new technologies and applying them to solve real-world problems. I am a team player and a good communicator, and I enjoy working with people from different backgrounds and cultures.

  I am most skilled in: <mark>C/C++</mark> and <mark>FreeRTOS</mark>.

  My mother tongue is <mark>Hebrew</mark>, and I am fluent in <mark>English</mark> and very good in <mark>Mandarin Chinese</mark>.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TandemG
        sub_title: RT Embedded Team Lead
        caption: June 2022 - Present
        description: | # this will include new lines to allow paragraphs
            Leading a team of 3 developers on several different projects while maintaining 2 projects myself.
              - Handling the full development cycle from requirements gathering and design to production release and CI/CD.
              - Using project management tools such as <mark>Git</mark>, <mark>Jira</mark>, <mark>Gerrit</mark>, <mark>Gitlab</mark>, <mark>Github</mark>, and <mark>Bitbucket</mark>.
              - Managing communication between the team and the customer and also with development teams in other countries. 

      - layout: left
        title: TandemG
        sub_title: RT Embedded Software developer
        caption: December 2020 - June 2022
        description: | # this will include new lines to allow paragraphs
            Developing and maintaining RT embedded software for several different products in the fields of home IOT, agriculture and medical.
              - Designing and implementing drivers, features and protocols in different enviorments using mostly <mark>C/C++</mark> and <mark>FreeRTOS</mark>.
              - Experience on microcontrollers such as <mark>STM32</mark>, <mark>ESP32</mark>, <mark>PIC32</mark>, <mark>NRF52</mark>.
              - Experience on <mark>FreeRTOS</mark>, <mark>ESP-IDF</mark>, <mark>Baremetal</mark>.
              - Experience on communication protocols such as <mark>MQTT</mark>, <mark>HTTP</mark>, <mark>TCP/IP</mark>, <mark>I2C</mark>, <mark>SPI</mark>, <mark>UART</mark>, <mark>Modbus</mark>, etc..
      - layout: left
        title: Independent
        sub_title: Chinese tour guide
        caption: August 2017 - January 2020
        description: | # this will include new lines to allow paragraphs
            Independent tour guide for Chinese speaking tourists, delegations etc. Performed multilingual translation for business groups in universities and companies.
      - layout: left
        title: NICE Systems
        sub_title: QA and Integration Engineer
        caption: August 2011 - November 2012
        description: | # this will include new lines to allow paragraphs
              Performed tests and integration of a recording solution software at clients location in several different countries.           
              Gained experience with SQL, Linux, Windows, and networking.
      - layout: left
        title: IDF/8200
        sub_title: ELINT (Electronic Intelligence) Operator
        caption: August 2008 - August 2011
        description: | # this will include new lines to allow paragraphs
              Performed ELINT (Electronic Intelligence) operations on several different platforms.
              Gained experience with RF, Radar and communication systems.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Experis Academy
        caption: 2020
        sub_title: Core C/C++

      - layout: top-middle
        title: Haifa University Tourism School
        caption: 2017 - 2019
        sub_title: Tour guide license
          
      - layout: top-middle
        title: South Western University of Finance and Economics (Chengdu, China)
        caption: 2015 - 2017
        sub_title: Chinese Language and Culture
        
      - layout: top-middle
        title: Rimon school of music
        caption: 2014 - 2015
        sub_title: Music production and sound engineering
        
      - layout: top-middle
        title: Aleh School of Science and Arts, Lod
        caption: 2004 - 2008
        sub_title: Full matriculation with major in computer science
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in embedded and software engineering some of my other interests and hobbies are:
      - ⛺ Traveling and exploring new places and cultures.
      - 👲 History and archeology.
      - 🎸 [Playing the guitar](https://www.facebook.com/moran.rozenszajn/videos/10158156871189034) and other instruments.
      - 💻 Writing code for [fun...](https://github.com/Moran296/moranometer)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
